### ISSUE TITLE
TestFX Maven

### ISSUE THREAD

**Issue by kayjay05** [pargmer/SE_PR_SS19#3]
Ich habe es gibt hier ein Problem um testFX in Eclipse zum Laufen zu bekommen. 
https://github.com/TestFX/TestFX
Hier ist eine detaillierte Anleitung, jedoch wenn ich die Maven Dependencies hinzufüge, läuft es nicht.

**Comment by pargmer** [comment]
Ich schaue es mir grad an.
Mit richtigen Java Version und dem Codestück sollte es eig passen...
 `<dependency>
    <groupId>org.testfx</groupId>
    <artifactId>testfx-core</artifactId>
    <version>4.0.15-alpha</version>
    <scope>test</scope>
</dependency>`

**Comment by erkut57** [comment]
JavaFx Version 8.0 wird verwendet -> dependencies müssen nicht hinzugefügt werden
